<?php
/**
 * Bookings table. slot_lock is generated by the database: 1 while a booking holds its slot.
 * Read queries join courts, venues, users, customer_profiles, payments and refunds for labels only.
 */
class BookingModel extends Model
{
    private const DETAIL_SELECT = "
        SELECT b.id, b.customer_id, b.court_id, b.slot_date, b.start_time, b.amount, b.payment_method, b.status,
               b.pending_expires_at, b.confirmed_at, b.released_at, b.cancelled_by, b.cancelled_at, b.cancel_reason,
               b.cancellation_class, b.rejection_reason, b.created_at,
               c.name AS court_name, v.id AS venue_id, v.name AS venue_name, v.slug AS venue_slug,
               v.address AS venue_address, v.owner_id, s.name AS sport_name,
               u.name AS customer_name, u.email AS customer_email, u.phone AS customer_phone,
               cp.reliability_score, cp.reliability_tier, cp.completed_count, cp.no_show_count,
               (SELECT p.order_id FROM payments p
                WHERE p.booking_id = b.id AND p.status = 'paid' ORDER BY p.id DESC LIMIT 1) AS paid_order_id,
               (SELECT r.percentage FROM refunds r JOIN payments p ON p.id = r.payment_id
                WHERE p.booking_id = b.id ORDER BY r.id DESC LIMIT 1) AS refund_percent,
               (SELECT r.amount FROM refunds r JOIN payments p ON p.id = r.payment_id
                WHERE p.booking_id = b.id ORDER BY r.id DESC LIMIT 1) AS refund_amount
        FROM bookings b
        JOIN courts c ON c.id = b.court_id
        JOIN venues v ON v.id = c.venue_id
        JOIN sport_types s ON s.id = c.sport_type_id
        JOIN users u ON u.id = b.customer_id
        JOIN customer_profiles cp ON cp.customer_id = b.customer_id";

    public function create(int $customerId, int $courtId, string $date, string $time, float $amount, string $method, string $status, ?string $expiresAt): int
    {
        return $this->insert(
            'INSERT INTO bookings (customer_id, court_id, slot_date, start_time, amount, payment_method, status, pending_expires_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
            'iissdsss',
            [$customerId, $courtId, $date, $time, $amount, $method, $status, $expiresAt]
        );
    }

    public function find(int $id): ?array
    {
        return $this->selectOne(self::DETAIL_SELECT . ' WHERE b.id = ?', 'i', [$id]);
    }

    public function forCustomer(int $customerId): array
    {
        return $this->select(
            self::DETAIL_SELECT . ' WHERE b.customer_id = ? ORDER BY b.slot_date DESC, b.start_time DESC, b.id DESC',
            'i',
            [$customerId]
        );
    }

    /** Bookings on every court of the owner's venues. */
    public function forOwner(int $ownerId): array
    {
        return $this->select(
            self::DETAIL_SELECT . ' WHERE v.owner_id = ? ORDER BY b.slot_date DESC, b.start_time DESC, b.id DESC',
            'i',
            [$ownerId]
        );
    }

    /** Must run inside a transaction; the row stays locked until commit or rollback. */
    public function lockForUpdate(int $id): ?array
    {
        return $this->selectOne(
            'SELECT id, customer_id, court_id, slot_date, start_time, amount, payment_method, status, pending_expires_at
             FROM bookings WHERE id = ? FOR UPDATE',
            'i',
            [$id]
        );
    }

    /** Start times on the date that a booking currently holds. */
    public function heldStarts(int $courtId, string $date): array
    {
        $rows = $this->select(
            'SELECT start_time FROM bookings WHERE court_id = ? AND slot_date = ? AND slot_lock = 1',
            'is',
            [$courtId, $date]
        );
        return array_column($rows, 'start_time');
    }

    /** Holding and released bookings on one slot, locked for the caller's transaction. */
    public function onSlotForUpdate(int $courtId, string $date, string $time): array
    {
        return $this->select(
            "SELECT id, customer_id, slot_date, start_time, status, pending_expires_at
             FROM bookings
             WHERE court_id = ? AND slot_date = ? AND start_time = ? AND (slot_lock = 1 OR status = 'released')
             FOR UPDATE",
            'iss',
            [$courtId, $date, $time]
        );
    }

    /** Unpaid holds past their expiry and cash requests whose slot has started. */
    public function staleHolds(string $now): array
    {
        return $this->select(
            "SELECT id, customer_id, slot_date, start_time, status, pending_expires_at
             FROM bookings
             WHERE (status = 'pending_payment' AND pending_expires_at <= ?)
                OR (status = 'pending' AND TIMESTAMP(slot_date, start_time) <= ?)",
            'ss',
            [$now, $now]
        );
    }

    /** The status guard makes each change apply once, even when two requests race. */
    public function expire(int $id, string $fromStatus, string $now): int
    {
        return $this->execute(
            "UPDATE bookings SET status = 'expired'
             WHERE id = ? AND status = ?
               AND ((status = 'pending_payment' AND pending_expires_at <= ?)
                 OR (status = 'pending' AND TIMESTAMP(slot_date, start_time) <= ?))",
            'isss',
            [$id, $fromStatus, $now, $now]
        );
    }

    public function confirm(int $id, string $now): int
    {
        return $this->execute(
            "UPDATE bookings SET status = 'confirmed', confirmed_at = ? WHERE id = ? AND status = 'pending'",
            'si',
            [$now, $id]
        );
    }

    public function reject(int $id, string $reason): int
    {
        return $this->execute(
            "UPDATE bookings SET status = 'rejected', rejection_reason = ? WHERE id = ? AND status = 'pending'",
            'si',
            [$reason, $id]
        );
    }

    public function cancel(int $id, string $fromStatus, int $cancelledBy, string $now, ?string $reason, ?string $cancellationClass): int
    {
        return $this->execute(
            "UPDATE bookings
             SET status = 'cancelled', cancelled_by = ?, cancelled_at = ?, cancel_reason = ?, cancellation_class = ?
             WHERE id = ? AND status = ?",
            'isssis',
            [$cancelledBy, $now, $reason, $cancellationClass, $id, $fromStatus]
        );
    }
}
