<?php
/**
 * Session registrations table. active_lock is generated by the database: 1 while a registration is not cancelled.
 * Read queries join users, payments and refunds for labels only.
 */
class SessionRegistrationModel extends Model
{
    /** Live registrations (registered or awaiting payment) of one session. */
    public function countLive(int $sessionId): int
    {
        $row = $this->selectOne(
            "SELECT COUNT(*) AS n FROM session_registrations WHERE session_id = ? AND status IN ('registered', 'pending_payment')",
            'i',
            [$sessionId]
        );
        return (int) $row['n'];
    }

    /** Every registration of a session with the customer's name, the paid amount and any refund. */
    public function forSession(int $sessionId): array
    {
        return $this->select(
            "SELECT r.id, r.customer_id, r.status, r.amount, r.cancel_source, r.cancelled_at, r.created_at,
                    u.name AS customer_name, u.email AS customer_email,
                    (SELECT p.amount FROM payments p
                     WHERE p.registration_id = r.id AND p.status = 'paid' ORDER BY p.id DESC LIMIT 1) AS paid_amount,
                    (SELECT rf.amount FROM refunds rf JOIN payments p ON p.id = rf.payment_id
                     WHERE p.registration_id = r.id ORDER BY rf.id DESC LIMIT 1) AS refund_amount
             FROM session_registrations r
             JOIN users u ON u.id = r.customer_id
             WHERE r.session_id = ?
             ORDER BY r.created_at, r.id",
            'i',
            [$sessionId]
        );
    }

    /** Live registrations of a session, locked for the caller's transaction. */
    public function liveForSessionForUpdate(int $sessionId): array
    {
        return $this->select(
            "SELECT id, customer_id, status, amount FROM session_registrations
             WHERE session_id = ? AND status IN ('registered', 'pending_payment')
             ORDER BY id FOR UPDATE",
            'i',
            [$sessionId]
        );
    }

    public function cancelBySession(int $id, string $now): int
    {
        return $this->execute(
            "UPDATE session_registrations SET status = 'cancelled', cancel_source = 'session_cancelled', cancelled_at = ?
             WHERE id = ? AND status IN ('registered', 'pending_payment')",
            'si',
            [$now, $id]
        );
    }
}
